---
title: "temp_test"
author: "Erin M. Buchanan"
date: '2022-07-06'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
library(googlesheets4)
library(dplyr)
library(rorcid)
library(rio)
library(scholar)
library(purrr)
library(httr)
```

## Get Data

```{r}
DF <- read_sheet("https://docs.google.com/spreadsheets/d/1dSlIQXeLcFgkITyfy15_yAdtjct1AedjD6s5D4qTzCw/edit#gid=1698777071")
```

## Work on ORC 

```{r eval = F}
ORC <- DF %>% 
  filter(ORCID == "FIND")

for (i in 2447:nrow(ORC)){
#for (i in 1:10){ #temporary do a small number 
  
  # find possible candidates 
  possibles <- orcid_search(family_name = ORC$last[i], 
                            given_name = ORC$first[i])
  
  cat(i)
  cat("\n")
  
  # if nrow == 1 then figure out if there's a match
  if (nrow(possibles) == 1){
    ORC$ORCID[i] <- possibles$orcid
  }
  
  # be nice to api take a break 
  Sys.sleep(runif(1, 3, 5))
  
}

DF <- DF %>% 
  full_join(ORCF %>% select(first, last, ORCID), 
            by = c("first" = "first", "last" = "last"))

export(DF, "orc_final.xlsx")
```

## Scholar Function

```{r}
get_scholar <- function (last_name = "", first_name = "", affiliation = NA) 
{
    if (!any(nzchar(c(first_name, last_name)))) 
        stop("At least one of first and last name must be specified!")
    site <- getOption("scholar_site")
    url <- paste0(site, "/citations?view_op=search_authors&mauthors=", 
        first_name, "+", last_name, "&hl=en&oi=ao")
    page <- get_scholar_resp(url)
    if (is.null(page)) 
        return(NA)
    aa <- content(page, as = "text")
    ids <- stringr::str_extract_all(string = aa, pattern = ';user=.{12}')
    
    if (length(unlist(ids)) == 0) {
        message("No Scholar ID found.")
        return(NA)
    }
    ids <- ids %>% unlist %>% gsub(";user=", "", 
        .) %>% unique
    
    return(ids)
  }
```

## Get Scholar IDs

```{r}
scholars <- DF %>% filter(scholar == "FIND")
p_get_scholar_id <- possibly(get_scholar, otherwise = NA_character_)

nrow(scholars)
# we are on 1:50

for(i in 1:50) {
  
  possibles <- p_get_scholar_id(last_name = scholars$last[i], 
                                first_name = scholars$first[i])
  
  if (length(possibles) == 1) { scholars$scholar[i] <- possibles }
  
  # be nice to api take a break 
  Sys.sleep(runif(1, 3, 5))
  
  # if divisible by 10
  if (i %% 10 == 0){
    export(scholars, "scholars_update.xlsx")
  }
}


```




